football_team_manager/schedules/urls.py
from django.urls import path

from football_team_manager.schedules import views

urlpatterns = [
    path('schedule-details/<int:pk>/', views.schedule_details, name='schedule-details'),
    path('add-event/', views.add_event, name='add-event'),
    path('all-events/<int:pk>/', views.all_events, name='all-events'),
    path('game-events/<int:pk>/', views.game_events, name='game-events'),
    path('training-events/<int:pk>/', views.training_events, name='training-events'),
    path('event-analytics/<int:pk>/', views.event_analytics, name='event-analytics'),
    path('attend-functionality/<int:pk>/', views.attend_functionality, name='attend-functionality'),
    path('attend-functionality-to-false/<int:pk>/', views.attend_functionality_to_false, name='attend-functionality-to-false')
]

football_team_manager/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
urlpatterns = [
    path('admin/', admin.site.urls),
    path("players/", include("football_team_manager.players.urls")),
    path("teams/", include("football_team_manager.teams.urls")),
    path("leagues/", include("football_team_manager.leagues.urls")),
    path("accounts/", include("football_team_manager.accounts.urls")),
    path("schemes/", include("football_team_manager.schemes.urls")),
    path('schedules/', include('football_team_manager.schedules.urls')),
    path("", include("football_team_manager.common.urls")),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elif not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

football_team_manager/schedules/models.py
from django.contrib.auth import get_user_model
from django.db import models


UserModel = get_user_model()

class Event(models.Model):

    team_versus = models.CharField(
        max_length=200
    )

    date = models.DateField()

    time = models.TimeField()

    location = models.CharField(
        max_length=150
    )

    is_training = models.BooleanField(
        default=False,
        null=True,
        blank=True
    )

    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE
    )


class EventAttendance(models.Model):
    attended = models.BooleanField(
        default=False
    )

    timestamp = models.DateTimeField(
        auto_now_add=True
    )

    event = models.ForeignKey(
        to=Event,
        on_delete=models.CASCADE
    )

    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE
    )

football_team_manager/schedules/forms.py
from datetime import datetime

from django import forms
from django.core.exceptions import ValidationError

from football_team_manager.schedules.models import Event


class EventBaseForm(forms.ModelForm):

    class Meta:
        model = Event
        exclude = ("user", )

        widgets = {
            "date": forms.TextInput(attrs={"type": "date"}),
            "time": forms.TextInput(attrs={"type": "time"}),
            "location": forms.TextInput(attrs={"type": "location"}),
            "is_training": forms.CheckboxInput(attrs={"class": "form-check-input"})
        }


    def clean_date(self):
        date = self.cleaned_data["date"]

        date = datetime.combine(date, datetime.min.time())

        if date < datetime.now():
            raise ValidationError("You cannot enter a date that is passed!")

        return date

class CreateEventForm(EventBaseForm):
    pass

football_team_manager/schedules/views.py
from datetime import datetime

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.db.models.aggregates import Count
from django.shortcuts import render, redirect
from django.views.generic import DetailView

from football_team_manager.schedules.forms import CreateEventForm
from football_team_manager.schedules.models import Event, EventAttendance

from football_team_manager.teams.models import MyTeam

UserModel = get_user_model()

# class ScheduleDetails(DetailView):
#
#     model = Event
#     template_name = 'schedule/schedule_details.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#
#         context['my_team'] = self.request.user.myteam_set.first()
#
#         context['events'] = Event.objects.filter(
#             user=self.request.user
#         ).order_by('date')

@login_required
def schedule_details(request, pk):
    user = UserModel.objects.get(id=pk)

    if not request.user == user or not MyTeam.objects.filter(user=user):
        raise PermissionDenied()


    my_team = user.myteam_set.first()

    filtered_events = Event.objects.filter(
        user=user
    ).order_by("date", "time")

    for event in filtered_events:
        date = event.date
        date = datetime.combine(date, datetime.min.time())

        if date < datetime.now():
            event.delete()

    context = {
        "user": user,
        "my_team": my_team,
        "events": filtered_events
    }


    return render(request, 'schedule/schedule_details.html', context)


@login_required
def add_event(request):

    if not MyTeam.objects.filter(user=request.user):
        raise PermissionDenied()

    form = CreateEventForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            event = form.save(commit=False)

            event.user = request.user

            event.save()

            EventAttendance.objects.create(user=request.user, event=event, attended=False)

            return redirect('schedule-details', pk=request.user.pk)

    context = {
        "form": form
    }

    return render(request, 'schedule/add_event.html', context)


@login_required
def all_events(request, pk):
    user = UserModel.objects.get(id=pk)

    if not request.user == user or not MyTeam.objects.filter(user=user):
        raise PermissionDenied()

    my_team = request.user.myteam_set.first()

    events = Event.objects.filter(user=request.user).all().order_by("date", "time")

    context = {
        "events": events,
        'my_team': my_team
    }
    return render(request, 'schedule/schedule_details.html', context)



@login_required
def game_events(request, pk):
    user = UserModel.objects.get(id=pk)

    if not request.user == user or not MyTeam.objects.filter(user=user):
        raise PermissionDenied()

    my_team = request.user.myteam_set.first()

    events = Event.objects.filter(is_training=False, user=request.user).order_by("date", "time")

    context = {
        "events": events,
        'my_team': my_team
    }

    return render(request, 'schedule/schedule_details.html', context)


@login_required
def training_events(request, pk):
    user = UserModel.objects.get(id=pk)

    if not request.user == user or not MyTeam.objects.filter(user=user):
        raise PermissionDenied()

    my_team = request.user.myteam_set.first()

    events = Event.objects.filter(is_training=True, user=request.user).order_by("date", "time")

    context = {
        "events": events,
        'my_team': my_team
    }

    return render(request, 'schedule/schedule_details.html', context)


def event_analytics(request, pk):
    user = UserModel.objects.get(id=pk)

    if not request.user == user:
        raise PermissionDenied()

    total_events = Event.objects.filter(user=request.user).count()

    total_attendance = EventAttendance.objects.filter(user=request.user, attended=True).count()

    attendance_rate = (total_attendance / total_events) * 100 if total_events > 0 else 0

    event_attendance = EventAttendance.objects.filter(user=request.user).values('event__team_versus', 'event__is_training').annotate(
        total=Count('id'),
        attended=Count('id', filter=Q(attended=True))
    )

    context = {
        "total_events": total_events,
        "total_attendance": total_attendance,
        "attendance_rate": attendance_rate,
        "event_attendance": event_attendance
    }

    return render(request, "schedule/event_analytics.html", context)


def attend_functionality(request, pk):

    event = EventAttendance.objects.get(id=pk)

    event.attended = True

    event.save()

    return redirect(request.META["HTTP_REFERER"], user=request.user)


def attend_functionality_to_false(request, pk):
    event = EventAttendance.objects.get(id=pk)

    event.attended = False

    event.save()

    return redirect(request.META["HTTP_REFERER"], user=request.user)

templates/schedule/event_analytics.html
{% extends 'common/base.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Analytics</title>
</head>
<body>
    <div class="containers">
        <h1 class="title">Event Analytics</h1>
        <p class="summary">Total Events: {{ total_events }}</p>
        <p class="summary">Total Attendance: {{ total_attendance }}</p>
        <p class="summary">Attendance Rate: {{ attendance_rate }}%</p>

        <h2 class="sub-title">Event Attendance</h2>
        <table class="analytics-table">
            <thead>
                <tr>
                    <th>Event</th>
                    <th>Total</th>
                    <th>Attended</th>
                </tr>
            </thead>
            
            {% for event in event_attendance %}
            
            <tbody>
                
            {% if not event.event__is_training  %}
                <tr>
                    <td>Match vs {{ event.event__team_versus }}</td>
                    <td>{{ event.total }}</td>
                    <td>{{ event.attended }}</td>
                </tr>
                
            {% else %}    
                <tr>
                    <td>Training Session</td>
                    <td>{{ event.total }}</td>
                    <td>{{ event.attended }}</td>
                </tr>
            </tbody>
                
            {% endif %}
                
            {% empty %}    
                <h1 class="title">No events here!!</h1>
            {% endfor %}
        </table>
    </div>
</body>
</html>

{% endblock %}

templates/schedule/schedule_details.html
{% extends 'common/base.html' %}
{% block content %}
<div class="container flex-grow-1">
    <header class="text-center my-4">
        <h1 class="text-danger">{{ my_team.team_name }}</h1>
        <p class="lead">Upcoming Matches & Training Sessions</p>
    </header>
    
    <div class="filters text-center mb-4">
        <a href="{% url 'all-events' request.user.pk %}"><button class="btn btn-danger mx-2">All Events</button></a>
        <a href="{% url 'game-events' request.user.pk %}"><button class="btn btn-danger mx-2">Games Only</button></a>
        <a href="{% url 'training-events' request.user.pk %}"><button class="btn btn-danger mx-2">Training Sessions</button></a>
        <a href="{% url 'event-analytics' request.user.pk %}"><button class="btn btn-danger mx-2">Event Analytics</button></a>
    </div>
    
    <div class="event-list">
        {% for event in events %}
            <div class="event card mb-3 shadow-sm">
                <div class="card-body">
                    <h3 class="card-title text-primary">
                    
                        {% if not event.is_training %}
                            Match vs {{ event.team_versus }}
                        {% else %}
                            Training Session
                        {% endif %}
                    </h3>
                    <p class="card-text">🙋🏻‍♂️<strong>
                        Will you attend: 
                        <a href="{% url 'attend-functionality' event.eventattendance_set.first.pk %}"><i class="fa-solid fa-check" style="color: green;"></i></a>
                        <a href="{% url 'attend-functionality-to-false' event.eventattendance_set.first.pk %}"><i class="fa-solid fa-x" style="color: red;"></i></a>
                            </strong>
                    <p class="card-text">📅 <strong>Date:</strong> {{ event.date }}</p>
                    <p class="card-text">🕒 <strong>Time:</strong> {{ event.time }}</p>
                    <p class="card-text">📍 <strong>Location:</strong> {{ event.location }}</p>
                </div>
            </div>
            
        {% empty %}
            <h2 class="text-center no-events">No events here!</h2>
        {% endfor %}
    
     <div class="text-center mt-4">
        <a href="{% url 'add-event' %}" class="add-event">+ Add New Event</a>
    </div>    
    </div>
    
   
</div>
{% endblock %}