football_team_manager/common/urls.py
from django.urls import path

from football_team_manager.common import views

urlpatterns = [
    path("", views.Index.as_view(), name="index")
]

football_team_manager/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
urlpatterns = [
    path('admin/', admin.site.urls),
    path("players/", include("football_team_manager.players.urls")),
    path("teams/", include("football_team_manager.teams.urls")),
    path("leagues/", include("football_team_manager.leagues.urls")),
    path("accounts/", include("football_team_manager.accounts.urls")),
    path("schemes/", include("football_team_manager.schemes.urls")),
    path('schedules/', include('football_team_manager.schedules.urls')),
    path("", include("football_team_manager.common.urls")),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elif not settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

football_team_manager/common/models.py
from django.db import models

# Create your models here.

football_team_manager/leagues/models.py
from django.contrib.auth import get_user_model
from django.db import models

from football_team_manager.leagues.validators import validate_league_name

UserModel = get_user_model()

class League(models.Model):

    league_name = models.CharField(
        max_length=200,
        validators=[
            validate_league_name
        ]
    )

    country = models.CharField(
        max_length=200,
    )

    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE
    )

    def __str__(self):

        return self.league_name

football_team_manager/schemes/models.py
from django.contrib.auth import get_user_model
from django.db import models

from football_team_manager.schemes.choices import SchemeChoices

UserModel = get_user_model()

class Scheme(models.Model):

    scheme = models.CharField(
        choices=SchemeChoices.choices
    )

    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE
    )

football_team_manager/teams/models.py
from django.contrib.auth import get_user_model
from django.db import models

from football_team_manager.leagues.models import League
from football_team_manager.teams.validators import validate_team_players, validate_team_name

UserModel = get_user_model()

class Team(models.Model):

    team_name = models.CharField(
        max_length=100,
        validators=[
            validate_team_name
        ],
    )

    team_league = models.ForeignKey(
        to=League,
        on_delete=models.CASCADE,
        related_name="leagues",
        blank=True,
        null=True
    )

    players = models.IntegerField(
        validators=[
            validate_team_players
        ]
    )

    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.team_name


class MyTeam(models.Model):
    team_name = models.CharField(
        max_length=200
    )

    logo_url = models.URLField()

    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE
    )

football_team_manager/common/forms.py
from django import forms
from django.forms import TextInput


class SearchForm(forms.Form):

    player = forms.CharField(
        max_length=300,
        required=False,
        widget=TextInput(attrs={
            "placeholder": "Search for a player......"
        },
        ),
        label=""
    )

football_team_manager/common/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import TemplateView, ListView

from football_team_manager.common.forms import SearchForm
from football_team_manager.players.models import Player
from football_team_manager.schemes.models import Scheme


class Index(ListView):
    template_name = "common/index.html"
    model = Player
    paginate_by = 2
    context_object_name = "filtered_players"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["player_search_form"] = SearchForm(self.request.GET)

        return context

    def get_queryset(self):

        queryset = self.model.objects.all()

        if self.request.user.is_authenticated:
            queryset = queryset.filter(user=self.request.user)

        else:
            queryset = []

        if self.request.user.is_authenticated:
            if "player" in self.request.GET:
                player = self.request.GET.get("player")
                queryset = queryset.filter(name__icontains=player)

        return queryset

templates/common/base.html
{% load static %}
{% load get_leagues %}
{% load get_teams %}
{% load get_scheme %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Football Team Manager</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="https://pngimg.com/d/football_PNG52775.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<style>
    body {
        background-image: url("/static/images/background.jpg");
        background-repeat: no-repeat;
    }
</style>

<body>

    <div class="links">

        <a href="{% url "index" %}" class="ball-link-a"><img class="ball-link" src="/static/images/ball.png" alt=""></a>
            
            {% if not request.user.myteam_set.all %}
                <a href="{% url 'create-team-name' %}">Create MyTeam</a>
            {% endif %}
    
            {% if request.user.myteam_set.all %}
                
                <a href="{% url 'schedule-details' request.user.pk %}">Schedule Details</a>
                
            {% endif %}
    
            {% get_scheme as scheme %}
            {% if request.user.scheme_set.all %}
                {% if scheme %}
                    <a href="{% url 'create-league' %}" class="create-league">Create League</a>
                {% endif %}
            {% endif %}
    
            {% get_leagues as leagues %}
            {% if request.user.league_set.all %}
                {% if leagues %}
                    <a href="{% url 'create-team' %}" class="create-team">Create Team</a>
                {% endif %}    
            {% endif %}
    
            {% get_teams as teams %}
            {% if request.user.team_set.all %}
                 {% if teams %}    
                    <a href="{% url 'create-player' %}" class="create-player">Create Player</a> 
                {% endif %}
            {% endif %}
            
            {% get_scheme as scheme %}
                {% if request.user.myteam_set.all and not request.user.scheme_set.all %}
                    <a href="{% url 'create-scheme' %}">Create Scheme</a>  
                {% elif request.user.scheme_set.all %}
                    <a href="{% url 'scheme-details' scheme.pk %}">Scheme Details</a>  
                    
                {% endif %}
    
            {% if not request.user.is_authenticated %}
            <a href="{% url 'login' %}" class="login">Login</a>
            <a href="{% url 'register' %}" class="register">Register</a>
            
            {% else %}
            <a href="{% url 'logout' %}" class="logout">Logout</a>
            <a href="{% url 'profile-details' request.user.pk %}" class="profile-details">Profile</a>
                
            {% endif %}
      
    </div>
    
    {% block content %}
    	
    {% endblock %}

    <div class="base-footer">

        <footer>
            &copy;Rosen Rosenov Ivanov 2025 Football Team Manager
            <a href="http://instagram.com"><i class="fa-brands fa-instagram"></i></a>
            <a href="http://facebook.com"><i class="fa-brands fa-facebook"></i></a>
        </footer>

    </div>

</body>
</html>